### home
GET http://localhost:3001

### get all notes
GET http://localhost:3001/api/notes

### get one note
GET http://localhost:3001/api/notes/2

### get note doesn't exist
GET http://localhost:3001/api/notes/5