### get person info
GET http://localhost:3001/api/persons/info

### get all persons
GET http://localhost:3001/api/persons

### get person note
GET http://localhost:3001/api/persons/2

### get person doesn't exist
GET http://localhost:3001/api/persons/5

### delete one person
DELETE http://localhost:3001/api/persons/2

### add new person failed
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "content": "1111"
}

### add new person success
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "han",
    "number": "1111-2222"
}